function [C,Cdot,Cddot] = C_mat_derivs(MD_sym,MDdot_sym,MDdot_diffq_sym,MDdot_diffqdot_sym,MDdot_diffqddot_sym,q,qdot,qddot,qdddot)


sq = sin(q); cq = cos(q);
MD = double(subs(MD_sym,{'s2','s3','s4','s5','s6','s7',...
    'c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7'},{sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7)}));

C = MD - 0.5*MD';

MDdot = double(subs(MDdot_sym,{'s2','s3','s4','s5','s6','s7',...
    'c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7','qddot1','qddot2','qddot3','qddot4','qddot5','qddot6',...
    'qddot7'},{sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7),qddot(1),qddot(2),qddot(3),qddot(4),qddot(5),qddot(6),...
    qddot(7)}));

Cdot = MDdot - 0.5*MDdot';

MDdot_diffq = double(subs(MDdot_diffq_sym,{'s2','s3','s4','s5','s6','s7',...
    'c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7','qddot1','qddot2','qddot3','qddot4','qddot5','qddot6',...
    'qddot7'},{sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7),qddot(1),qddot(2),qddot(3),qddot(4),qddot(5),qddot(6),...
    qddot(7)}));

MDdot_diffqdot = double(subs(MDdot_diffqdot_sym,{'s2','s3','s4','s5','s6','s7',...
    'c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7','qddot1','qddot2','qddot3','qddot4','qddot5','qddot6',...
    'qddot7'},{sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7),qddot(1),qddot(2),qddot(3),qddot(4),qddot(5),qddot(6),...
    qddot(7)}));

MDdot_diffqddot = double(subs(MDdot_diffqddot_sym,{'s2','s3','s4','s5','s6','s7',...
    'c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7','qddot1','qddot2','qddot3','qddot4','qddot5','qddot6',...
    'qddot7'},{sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7),qddot(1),qddot(2),qddot(3),qddot(4),qddot(5),qddot(6),...
    qddot(7)}));

MDddot = reshape(MDdot_diffq,[7,49])*kron(eye(7),qdot) + ...
        reshape(MDdot_diffqdot,[7,49])*kron(eye(7),qddot) + ...
        reshape(MDdot_diffqddot,[7,49])*kron(eye(7),qdddot);
    
Cddot = MDddot + 0.5*MDddot';
end