function [f,fderivs_term,fdot] = fderivs_func_fdot(q,qdot,qddot,qdddot,J,Mc,ric_tip,...
    robot_const,Jdot_sym,Jddot_sym,Adot_sym,Ainvdot_sym,Addot_sym,...
    Ainvddot_sym,Jddot_diffq_sym,Jddot_diffqdot_sym,Jddot_diffqddot_sym,...
    Addot_diffq_sym,Addot_diffqdot_sym,Addot_diffqddot_sym)

% This function returns the spatial force applied by the arm at the end
% effector, and a term with derivatives of f given by
%
% fderivs_term = \ddot{J}'*f + 2\dot{J}^T\dot{f} + J^T\ddot{f}

[Rtemp, ~] = fwdkin(robot_const.kin, q);

A = [Rtemp zeros(3); Rtemp*hat(ric_tip), Rtemp];

Vc = A\(J*qdot);
omega = [Vc(1);Vc(2);Vc(3)];
bc = [hat(omega)*Mc(1:3,1:3)*omega;zeros(3,1)];

sq = sin(q); cq = cos(q);

Adot = double(subs(Adot_sym,{'s1','s2','s3','s4','s5','s6','s7',...
    'c1','c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7'},{sq(1),sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(1),cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7)}));

Jdot = double(subs(Jdot_sym,{'s1','s2','s3','s4','s5','s6','s7',...
    'c1','c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7'},{sq(1),sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(1),cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7)}));

alphac = A\(Jdot*qdot + J*qddot - Adot*Vc);

f = A'\(Mc*alphac + bc);

Jddot = double(subs(Jddot_sym,{'s1','s2','s3','s4','s5','s6','s7',...
    'c1','c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7','qddot1','qddot2','qddot3','qddot4','qddot5','qddot6',...
    'qddot7'},{sq(1),sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),cq(1),cq(2),cq(3),cq(4),...
    cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),qdot(6),...
    qdot(7),qddot(1),qddot(2),qddot(3),qddot(4),qddot(5),qddot(6),...
    qddot(7)}));

omegadot = [alphac(1);alphac(2);alphac(3)];
bc_dot = [hat(omegadot)*Mc(1:3,1:3)*omega + hat(omega)*Mc(1:3,1:3)*omegadot;zeros(3,1)];

Ainvdot = double(subs(Ainvdot_sym,{'s1','s2','s3','s4','s5','s6','s7',...
    'c1','c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7'},{sq(1),sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(1),cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7)}));

Addot = double(subs(Addot_sym,{'s1','s2','s3','s4','s5','s6','s7',...
    'c1','c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7','qddot1','qddot2','qddot3','qddot4','qddot5','qddot6',...
    'qddot7'},{sq(1),sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),cq(1),cq(2),cq(3),cq(4),...
    cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),qdot(6),...
    qdot(7),qddot(1),qddot(2),qddot(3),qddot(4),qddot(5),qddot(6),...
    qddot(7)}));

alphac_dot = Ainvdot'*(Jdot*qdot + J*qddot - Adot*Vc) + ...
    A'\(Jddot*qdot + 2*Jdot*qddot + J*qdddot - Addot*Vc - Adot*alphac);

fdot = Ainvdot'*(Mc*alphac + bc) + A'\(Mc*alphac_dot + bc_dot);

Ainvddot = double(subs(Ainvddot_sym,{'s1','s2','s3','s4','s5','s6','s7',...
    'c1','c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7','qddot1','qddot2','qddot3','qddot4','qddot5','qddot6',...
    'qddot7'},{sq(1),sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),cq(1),cq(2),cq(3),cq(4),...
    cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),qdot(6),...
    qdot(7),qddot(1),qddot(2),qddot(3),qddot(4),qddot(5),qddot(6),...
    qddot(7)}));

omegaddot = [alphac_dot(1);alphac_dot(2);alphac_dot(3)];

bc_ddot = [(hat(omegaddot)*Mc(1:3,1:3)*omega +...
    2*hat(omegadot)*Mc(1:3,1:3)*omegadot + hat(omega)*Mc(1:3,1:3)*omegaddot);zeros(3,1)];

Jddot_diffq = double(subs(Jddot_diffq_sym,{'s1','s2','s3','s4','s5','s6','s7',...
    'c1','c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7','qddot1','qddot2','qddot3','qddot4','qddot5','qddot6',...
    'qddot7'},{sq(1),sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),cq(1),cq(2),cq(3),cq(4),...
    cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),qdot(6),...
    qdot(7),qddot(1),qddot(2),qddot(3),qddot(4),qddot(5),qddot(6),...
    qddot(7)}));

Jddot_diffqdot = double(subs(Jddot_diffqdot_sym,{'s1','s2','s3','s4','s5','s6','s7',...
    'c1','c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7'},{sq(1),sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(1),cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7)}));
    
Jddot_diffqddot = double(subs(Jddot_diffqddot_sym,{'s1','s2','s3','s4','s5','s6','s7',...
    'c1','c2','c3','c4','c5','c6','c7'},{sq(1),sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(1),cq(2),cq(3),cq(4),cq(5),cq(6),cq(7)}));

Addot_diffq = double(subs(Addot_diffq_sym,{'s1','s2','s3','s4','s5','s6','s7',...
    'c1','c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7','qddot1','qddot2','qddot3','qddot4','qddot5','qddot6',...
    'qddot7'},{sq(1),sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),cq(1),cq(2),cq(3),cq(4),...
    cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),qdot(6),...
    qdot(7),qddot(1),qddot(2),qddot(3),qddot(4),qddot(5),qddot(6),...
    qddot(7)}));

Addot_diffqdot = double(subs(Addot_diffqdot_sym,{'s1','s2','s3','s4','s5','s6','s7',...
    'c1','c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7'},{sq(1),sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(1),cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7)}));

Addot_diffqddot = double(subs(Addot_diffqddot_sym,{'s1','s2','s3','s4','s5','s6','s7',...
    'c1','c2','c3','c4','c5','c6','c7'},{sq(1),sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(1),cq(2),cq(3),cq(4),cq(5),cq(6),cq(7)}));

Jdddot = reshape(Jddot_diffq,[6,49])*kron(eye(7),qdot) + ...
        reshape(Jddot_diffqdot,[6,49])*kron(eye(7),qddot) + ...
        reshape(Jddot_diffqddot,[6,49])*kron(eye(7),qdddot);

Adddot = reshape(Addot_diffq,[6,42])*kron(eye(6),qdot) + ...
        reshape(Addot_diffqdot,[6,42])*kron(eye(6),qddot) + ...
        reshape(Addot_diffqddot,[6,42])*kron(eye(6),qdddot);

alphac_ddot = Ainvddot*(Jdot*qdot + J*qddot - Adot*Vc) + ...
    2*Ainvdot*(Jddot*qdot + 2*Jdot*qddot + J*qdddot - Addot*Vc - ...
    Adot*alphac) + A\(Jdddot*qdot + 3*Jddot*qddot + 3*Jdot*qdddot - ...
    Adddot*Vc - 2*Addot*alphac - Adot*alphac_dot);
fddot = Ainvddot'*(Mc*alphac + bc) + 2*Ainvdot'*(Mc*alphac_dot + bc_dot) + ...
    A'\(Mc*alphac_ddot + bc_ddot);

fderivs_term = Jddot'*f + 2*Jdot'*fdot + J'*fddot;
end