function [Mdot, Mddot, Mddot_diffq, Mddot_diffqdot, Mddot_diffqddot,t] = ...
    mass_mat_derivs(Mdot_sym, Mddot_sym, Mddot_diffq_sym, ...
    Mddot_diffqdot_sym, Mddot_diffqddot_sym,q,qdot,qddot)

sq = sin(q); cq = cos(q);

tic
Mddot_diffqddot = double(subs(Mddot_diffqddot_sym,{'s2','s3','s4','s5','s6','s7',...
    'c2','c3','c4','c5','c6','c7'},{sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(2),cq(3),cq(4),cq(5),cq(6),cq(7)}));
t(1) = toc;

Mddot_diffqdot = double(subs(Mddot_diffqdot_sym,{'s2','s3','s4','s5','s6','s7',...
    'c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7'},{sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7)}));
t(2) = toc;

Mddot_diffq = double(subs(Mddot_diffq_sym,{'s2','s3','s4','s5','s6','s7',...
    'c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7','qddot1','qddot2','qddot3','qddot4','qddot5','qddot6',...
    'qddot7'},{sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7),qddot(1),qddot(2),qddot(3),qddot(4),qddot(5),qddot(6),...
    qddot(7)}));
t(3) = toc;

Mddot = double(subs(Mddot_sym,{'s2','s3','s4','s5','s6','s7',...
    'c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7','qddot1','qddot2','qddot3','qddot4','qddot5','qddot6',...
    'qddot7'},{sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7),qddot(1),qddot(2),qddot(3),qddot(4),qddot(5),qddot(6),...
    qddot(7)}));
t(4) = toc;

Mdot = double(subs(Mdot_sym,{'s2','s3','s4','s5','s6','s7',...
    'c2','c3','c4','c5','c6','c7','qdot1','qdot2','qdot3','qdot4','qdot5',...
    'qdot6','qdot7'},{sq(2),sq(3),sq(4),sq(5),sq(6),sq(7),...
    cq(2),cq(3),cq(4),cq(5),cq(6),cq(7),qdot(1),qdot(2),qdot(3),qdot(4),qdot(5),...
    qdot(6),qdot(7)}));
t(5) = toc;

end